name: Deploy Markdown to GitHub Pages

on:
  # Runs on pushes to your main branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This action converts your .md files to .html
      - name: Convert Markdown to Pages
        uses: wranders/markdown-to-pages-action@v1
        with:
          # Tell it which .md files to convert
          files: |
            README.md
            src/main/java/com/sudha/design/lld/ducks/Strategy.md
            src/main/java/com/sudha/design/lld/merge/Composite.md
            src/main/java/com/sudha/design/lld/merge/Iterator.md
            src/main/java/com/sudha/design/lld/caffeine/Template.md
            src/main/java/com/sudha/design/lld/chocolate/Singleton.md
            src/main/java/com/sudha/design/lld/hometheatre/Facade.md
            src/main/java/com/sudha/design/lld/coffee/Decorator.md
            src/main/java/com/sudha/design/lld/weather/Observer.md
            src/main/java/com/sudha/design/lld/birds/Adapter.md
            src/main/java/com/sudha/design/lld/pizza/abstractfactory/AbstractFactory.md
            src/main/java/com/sudha/design/lld/pizza/simple/SimpleFactory.md
            src/main/java/com/sudha/design/lld/pizza/factory/Factory.md
            src/main/java/com/sudha/design/lld/remote/Command.md
            # Add any other .md files here

      # This is the standard GitHub action to upload the built site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # The 'dist' folder is where the action above puts the .html files

  # This job does the actual deployment
  deploy-site:
    needs: deploy # Wait for the 'deploy' job to finish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
